package com.jds.jn.gui.forms;

import org.apache.log4j.spi.LoggingEvent;

import javax.swing.*;

import java.awt.*;
import java.awt.event.*;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

/**
 * Author: VISTALL
 * Company: J Develop Station
 * Date:  11:56:46/20.07.2010
 */
public class ConsoleForm extends JFrame
{
	private static ConsoleForm _instance;
	private JPanel _rootPane;
	private JTextPane _console;

	public static ConsoleForm getInstance()
	{
		if(_instance == null)
		{
			_instance = new ConsoleForm();
		}

		return _instance;
	}

	private ConsoleForm()
	{
		super("Console Form");
		$$$setupUI$$$();
		add($$$getRootComponent$$$());
		setSize(new Dimension(600, 800));
		setResizable(false);
		$$$getRootComponent$$$().registerKeyboardAction(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				ConsoleForm.this.setVisible(false);
			}
		}, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);
	}

	public void log(LoggingEvent val)
	{
		String loggerName = val.getLoggerName();
		try
		{
			Class l = Class.forName(val.getLoggerName());
			loggerName = l.getSimpleName();
		}
		catch(ClassNotFoundException e)
		{
		}

		String text = "[" + loggerName + "] " + val.getMessage();
		writeText(text);
		if(val.getThrowableInformation() != null)
		{
			String t = stackTrace(val.getThrowableInformation().getThrowable());

			writeText(t);
		}
	}

	private void writeText(String t)
	{
		_console.setText(_console.getText() + t + "\n");
	}

	public String stackTrace(Throwable e)
	{
		String ee = e.getMessage();
		StackTraceElement[] trace = e.getStackTrace();

		for(StackTraceElement aTrace : trace)
		{
			if(aTrace == null)
			{
				continue;
			}
			ee = ee + "\n\tat " + aTrace;
		}
		return ee;
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		_rootPane = new JPanel();
		_rootPane.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		final JScrollPane scrollPane1 = new JScrollPane();
		scrollPane1.setVerticalScrollBarPolicy(22);
		_rootPane.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		_console = new JTextPane();
		_console.setAutoscrolls(false);
		_console.setBackground(new Color(-16777216));
		_console.setEditable(false);
		_console.setForeground(new Color(-1));
		scrollPane1.setViewportView(_console);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{
		return _rootPane;
	}
}
