package com.jds.jn.gui.panels;

import javax.swing.*;

import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.jds.jn.gui.models.DecPacketTableModel;
import com.jds.jn.gui.models.NotDecPacketTableModel;
import com.jds.jn.gui.panels.viewpane.*;
import com.jds.jn.gui.panels.viewpane.packetlist.DecPacketListPane;
import com.jds.jn.gui.panels.viewpane.packetlist.NotDecPacketListPane;
import com.jds.jn.session.Session;
import com.jds.jn.util.Bundle;

/**
 * Author: VISTALL
 * Company: J Develop Station
 * Date: 26.08.2009
 * Time: 17:15:02
 */
public class ViewPane extends JPanel
{
	public Session _session;

	private JPanel mainPane;
	private JTabbedPane _packetAndSearch;
	private DecPacketTableModel _decryptPacketTableModel = new DecPacketTableModel(this);
	private NotDecPacketTableModel _notDecryptPacketTableModel = new NotDecPacketTableModel(this);

	private PacketList _packetList;
	private SearchPane _searchPane;
	private FilterPane _filterPane;
	private InfoPane _infoPane;

	private JPopupMenu _tabMenu;

	public ViewPane(Session session)
	{
		$$$setupUI$$$();

		_session = session;

		_tabMenu = new JPopupMenu();

		_packetAndSearch.addMouseListener(new MouseListener()
		{

			@Override
			public void mouseClicked(MouseEvent e)
			{
				if (e.getClickCount() == 1 && e.getButton() == MouseEvent.BUTTON3)
				{
					_tabMenu.show(_packetAndSearch, e.getX(), e.getY());
				}
			}

			@Override
			public void mousePressed(MouseEvent e)
			{

			}

			@Override
			public void mouseReleased(MouseEvent e)
			{

			}

			@Override
			public void mouseEntered(MouseEvent e)
			{

			}

			@Override
			public void mouseExited(MouseEvent e)
			{

			}
		});


		_infoPane = new InfoPane();
		_searchPane = new SearchPane(this);
		_filterPane = new FilterPane(this);
		_packetList = new PacketList(this);
	}

	public void drawThis()
	{
		_filterPane.drawThis();

		_packetAndSearch.addTab(Bundle.getString("PacketList"), _packetList);
		_packetAndSearch.addTab(Bundle.getString("FindPanel"), _searchPane);
		_packetAndSearch.addTab(Bundle.getString("Filter"), _filterPane);
		_packetAndSearch.addTab(Bundle.getString("Info"), _infoPane);
	}

	public int getIndex(Component comp)
	{
		int size = _packetAndSearch.getComponentCount();

		for (int i = 0; i < size; i++)
		{
			Component com = _packetAndSearch.getComponent(i);
			if (com.equals(comp))
			{
				return i;
			}
		}

		return -1;
	}

	private void createUIComponents()
	{
		mainPane = this;

		setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
	}

	public void close()
	{

	}

	public DecPacketTableModel getDecryptPacketTableModel()
	{
		return _decryptPacketTableModel;
	}

	public NotDecPacketTableModel getNotDecryptPacketTableModel()
	{
		return _notDecryptPacketTableModel;
	}

	public Session getSession()
	{
		return _session;
	}

	public DecPacketListPane getPacketListPane()
	{
		return _packetList.get_packetListPane();//_Dec_packetListPane;
	}

	public NotDecPacketListPane getNotDecPacketListPane()
	{
		return _packetList.getNotDecPacketListPane();//_notdec_packetListPane;
	}

	public SearchPane getSearchPane()
	{
		return _searchPane;
	}

	public FilterPane getFilterPane()
	{
		return _filterPane;
	}

	public void updateInfo(Session session)
	{
		_infoPane.update(session);
	}

	public void actionEnable(boolean e)
	{
		setEnabled(e);

		_packetList.setEnabled(e);
	}

	public JTabbedPane getPacketAndSearch()
	{
		return _packetAndSearch;
	}

	public PacketList getPacketList()
	{
		return _packetList;
	}

	public InfoPane getInfoPane()
	{
		return _infoPane;
	}

	public JPopupMenu getTabMenu()
	{
		return _tabMenu;
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		createUIComponents();
		mainPane.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		_packetAndSearch = new JTabbedPane();
		_packetAndSearch.setTabPlacement(2);
		mainPane.add(_packetAndSearch, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{
		return mainPane;
	}
}
