package com.jds.jn.gui.panels.viewpane;

import javax.swing.*;

import java.awt.*;
import java.awt.event.*;
import java.util.ResourceBundle;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.jds.jn.gui.panels.ViewPane;
import com.jds.jn.gui.panels.viewpane.packetlist.DecPacketListPane;
import com.jds.jn.gui.panels.viewpane.packetlist.NotDecPacketListPane;

/**
 * Author: VISTALL
 * Company: J Develop Station
 * Date: Sep 29, 2009
 * Time: 10:00:48 PM
 */
public class PacketList extends JPanel
{
	private JPanel root;
	private boolean _isHide = false;
	protected NotDecPacketListPane _notDecPacketListPane;
	protected DecPacketListPane _decPacketListPane;
	protected ViewPane _pane;

	private JRadioButton radio1;
	private JRadioButton radio2;
	private JPopupMenu popup;

	public PacketList(ViewPane pane)
	{
		_pane = pane;
		$$$setupUI$$$();

		_notDecPacketListPane = new NotDecPacketListPane(_pane);
		_decPacketListPane = new DecPacketListPane(_pane);

		popup = new JPopupMenu();


		radio1 = new JRadioButton(ResourceBundle.getBundle("com/jds/jn/resources/bundle/LanguageBundle").getString("DecodeList"));

		radio1.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				PacketList.this.remove(_notDecPacketListPane);
				add(_decPacketListPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
				updateUI();
			}
		});

		radio2 = new JRadioButton(ResourceBundle.getBundle("com/jds/jn/resources/bundle/LanguageBundle").getString("NotDecodeList"));
		radio2.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				PacketList.this.remove(_decPacketListPane);
				add(_notDecPacketListPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
				updateUI();
			}
		});

		registerKeyboardAction(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				popup.show(PacketList.this, 0, 0);
			}
		}, KeyStroke.getKeyStroke(KeyEvent.VK_Q, InputEvent.CTRL_MASK), JComponent.WHEN_IN_FOCUSED_WINDOW);

		ButtonGroup group = new ButtonGroup();

		group.add(radio1);
		group.add(radio2);

		popup.add(radio1);
		popup.add(radio2);

		addMouseListener(new MouseListener()
		{

			@Override
			public void mouseClicked(MouseEvent e)
			{
				if (e.getButton() == MouseEvent.BUTTON3)
				{
					popup.show(PacketList.this, e.getX(), e.getY());
				}
			}

			@Override
			public void mousePressed(MouseEvent e)
			{

			}

			@Override
			public void mouseReleased(MouseEvent e)
			{

			}

			@Override
			public void mouseEntered(MouseEvent e)
			{

			}

			@Override
			public void mouseExited(MouseEvent e)
			{

			}
		});
	}

	@Override
	public void setEnabled(boolean b)
	{
		_decPacketListPane.setEnabled(b);
		_notDecPacketListPane.setEnabled(b);

		super.setEnabled(b);
	}

	public DecPacketListPane get_packetListPane()
	{
		return _decPacketListPane;
	}

	public NotDecPacketListPane getNotDecPacketListPane()
	{
		return _notDecPacketListPane;
	}

	private void createUIComponents()
	{
		root = this;
		setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
	}

	public boolean isHide()
	{
		return _isHide;
	}

	public void setIsHide(boolean IS_HIDE)
	{
		this._isHide = IS_HIDE;
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		createUIComponents();
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{
		return root;
	}
}
