package com.jds.jn.gui.panels.viewpane.packetlist;

import java.awt.Insets;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.jds.jn.gui.forms.PacketForm;
import com.jds.jn.gui.panels.ViewPane;
import com.jds.jn.gui.renders.PacketTableRenderer;
import com.jds.jn.network.packets.DecryptedPacket;

/**
 * @author VISTALL
 * @date 17:11/20.09.2011
 */
public class UnknownPacketListPane extends JPanel
{
	private class MouseListenerImpl extends MouseAdapter
	{
		@Override
		public void mouseClicked(MouseEvent e)
		{
			int row = _table.rowAtPoint(e.getPoint());

			if(e.getClickCount() == 2 && e.getButton() == MouseEvent.BUTTON1)
			{
				if(row == -1)
					return;

				DecryptedPacket packet = _viewPane.getUnknownPacketListModel().getPacket(row);

				if(packet == null)
					return;

				new PacketForm(_viewPane, 1.F, packet, row);
			}
		}
	}

	private JPanel _root;
	private JTable _table;

	private ViewPane _viewPane;

	public UnknownPacketListPane(ViewPane pane)
	{
		_viewPane = pane;

		$$$setupUI$$$();
	}

	private void createUIComponents()
	{
		_root = this;

		setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));

		_table = new JTable(_viewPane.getUnknownPacketListModel());
		_table.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		_table.setDefaultRenderer(Object.class, new PacketTableRenderer(_viewPane.getUnknownPacketListModel()));
		_table.getColumnModel().getColumn(0).setMaxWidth(30); //type
		_table.getColumnModel().getColumn(1).setMaxWidth(115); //time
		_table.getColumnModel().getColumn(2).setMaxWidth(50); //id
		_table.getColumnModel().getColumn(3).setMaxWidth(50);  //lenght
		_table.getColumnModel().getColumn(4).setMaxWidth(180); //name

		_table.addMouseListener(new MouseListenerImpl());
	}

	public JTable getPacketTable()
	{
		return _table;
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		createUIComponents();
		_root.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		final JScrollPane scrollPane1 = new JScrollPane();
		scrollPane1.setVerticalScrollBarPolicy(22);
		_root.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		scrollPane1.setViewportView(_table);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{
		return _root;
	}
}
